choria-io/packager

Dockerfile.buster-go1.14

Add buster 64 image
Fix the softhsm installation in c8

Add buster, fix softhsm c8

---

Dockerfile.buster-go1.14
Dockerfile.el6-go1.14
Dockerfile.el7-go1.14
Dockerfile.el7-go1.14-puppet
Dockerfile.el8-go1.14
Dockerfile.stretch-go1.14
Dockerfile.xenial-go1.14

(misc) update go to latest

---

Dockerfile.bullseye-go

Signed-off-by: Franciszek Klajn <fklajn@opera.com>

Add support for Debian Bullseye

---

.github/workflows/el8-go.yaml

(misc) send build args to docker

---

.github/workflows/el8-go.yaml

reusable action

---

.github/actions/build-packager/action.yaml
.github/workflows/el8-go.yaml

pass secrets to the action

---

.github/actions/build-packager/action.yaml

fix resolving go version

---

.github/workflows/containers.yaml

build debian package using correct buster image

---

.github/workflows/containers.yaml

(misc) go 1.17.3

---

.github/workflows/containers.yaml

update go to 1.17.4

---

.github/workflows/containers.yaml

(misc) update to go 1.17.6

---

.github/workflows/containers.yaml

update to go 1.17.7

---

.github/workflows/containers.yaml

upgrade builders to 1.18

---

Dockerfile.bionic-go
Dockerfile.bullseye-go
Dockerfile.buster-go
Dockerfile.el7-go
Dockerfile.el7-puppet-go
Dockerfile.el8-go
Dockerfile.focal-go
install-choria.sh

This will be used for automated testing of the
package repos and modules

(misc) add a choria install helper

---

.github/workflows/containers.yaml
install-choria.sh

(misc) Update to go 1.18.1

---

install-choria.sh

fix install on el8

---

lib/packager/compile_target.rb

(misc) pass trimpath to go build

---

lib/packager/compile_target.rb

(misc) pass trimpath to build not ld

---

.github/workflows/containers.yaml

(misc) Update to go 1.18.3

---

.github/workflows/containers.yaml
Dockerfile.el9-go

(misc) add el9 support

---

Dockerfile.el9-go

(misc) adjust for el9 changes

---

.github/workflows/containers.yaml

(misc) fix el9 container name

---

.github/workflows/containers.yaml
Dockerfile.jammy-go
install-choria.sh

Only merge after puppetlabs has released their jammy packages! Or else it will fail.

Add packages for ubuntu jammy

---

lib/packager/compile_target.rb

(#52) Disable go build vcs integration

---

Dockerfile.el9-go
brp-strip

(#54) restore old strip behavior for el9

---

.github/workflows/containers.yaml

(misc) upgrade to 1.18.5

---

.github/workflows/containers.yaml

prepare containers for go 1.19 testing

---

.github/workflows/containers.yaml

(misc) update go to 1.19.1

---

Dockerfile.debian-go

(misc) go now uses stretch not buster

---

Dockerfile.debian-go

(misc) fix distro name for latest debian

---

.github/workflows/containers.yaml

(misc) update go to 1.19.2

---

.github/workflows/containers.yaml

(misc) update go to 1.19.3

---

.github/workflows/containers.yaml

(misc) update go to 1.19.4

---

.github/workflows/containers.yaml

update go go 1.19.5
